[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run serve"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[build.watchPatterns]]
paths = ["src/**", "public/**", "package.json"]