[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'python310Packages.virtualenv']

[phases.install]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate && pip install --upgrade pip',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase complete - with auth system"']

[start]
cmd = '. /opt/venv/bin/activate && python -m uvicorn src.a3e.main:app --host 0.0.0.0 --port $PORT'
