providers = ["python"]

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'pip install gunicorn'
]

[phases.build]
cmds = []

[start]
cmd = 'gunicorn subscription_backend:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
