[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "No build step needed"']

[start]
cmd = 'python -m uvicorn railway_test_api:app --host 0.0.0.0 --port $PORT'
