[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc", "libpq"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn src.a3e.main:app --host 0.0.0.0 --port ${PORT:-8000}"
