[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/a3e/main_production.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
startCommand = "python src/a3e/main_production.py"
