[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_app.py"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
startCommand = "python run_app.py"
