[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.simple"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8000" }
PYTHONPATH = { default = "/app" }
DEBUG = { default = "false" }
