[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn src.a3e.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
startCommand = "uvicorn src.a3e.main:app --host 0.0.0.0 --port $PORT --workers 4"
