[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -c 'python -m uvicorn src.a3e.main:app --host 0.0.0.0 --port ${PORT:-8000}'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
