"""Add agent_workflows table

Revision ID: add_agent_workflows
Revises: 93dac6dcdc1a
Create Date: 2025-09-04 17:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_agent_workflows'
down_revision = '93dac6dcdc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_workflows',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('institution_id', sa.String(length=36), nullable=False),
        sa.Column('workflow_type', sa.String(length=50), nullable=False),
        sa.Column('accreditor_id', sa.String(length=20), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='processingstatus'), nullable=True),
        sa.Column('current_agent', sa.String(length=50), nullable=True),
        sa.Column('round_number', sa.Integer(), nullable=True),
        sa.Column('max_rounds', sa.Integer(), nullable=True),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('output_data', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['accreditor_id'], ['accreditors.id'], ),
        sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_workflows')
    # ### end Alembic commands ###
