name: native-package-and-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test-package:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-production.txt ]; then pip install -r requirements-production.txt; elif [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements file"; fi
          pip install gunicorn uvicorn
      - name: Run tests
        run: |
          if [ -d tests ]; then pytest -q; else echo 'No tests'; fi
      - name: Package artifact
        run: |
          mkdir -p dist
          tar -czf dist/mapmystandards_$(date +%Y%m%d_%H%M%S).tar.gz requirements.txt subscription_backend.py src web native_deploy Dockerfile || true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: mapmystandards-native
            path: dist/*.tar.gz

  
