name: native-package-and-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test-package:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn uvicorn
      - name: Run tests
        run: |
          if [ -d tests ]; then pytest -q; else echo 'No tests'; fi
      - name: Package artifact
        run: |
          mkdir -p dist
          tar -czf dist/mapmystandards_$(date +%Y%m%d_%H%M%S).tar.gz requirements.txt subscription_backend.py src web native_deploy Dockerfile || true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: mapmystandards-native
            path: dist/*.tar.gz
      - name: Optional remote deploy
        if: ${{ secrets.DEPLOY_HOST && secrets.DEPLOY_USER && secrets.DEPLOY_KEY }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            WORKDIR=/opt/mapmystandards
            sudo mkdir -p $WORKDIR
            sudo chown $USER:$USER $WORKDIR
            cd $WORKDIR
            echo 'Retrieve artifact & deploy (customize this block).'
            if [ -f native_deploy/deploy_fastapi.sh ]; then bash native_deploy/deploy_fastapi.sh; fi
